### ISSUE TITLE
X11 is unstable with the 2016.06 LiveISO on a Celeron N3150 with CherryView graphics

### ISSUE THREAD

**Issue by RJVB** [KaOSx/live-uefi#11]
As stated in the subject, the current LiveISO runs into graphics (probably compositing) issues on my W510UL notebook with Intel Celeron N3150 CPU with integrated i915 "CherryView" graphics. This is strange because a laptop with a considerably more recent 6th gen i3/SkyLake CPU/IGP works just fine.

Stability is a little bit better when using the i915.preliminary_hw_support=1 boot parameter but still inacceptable.

I had already observed this with a home-built 4.6.2 kernel used with Ubuntu 14.04 and was hoping that it was due to other software (X11, Mesa) being too old. I'm getting much better results with kernel 4.5.7 .

This is mostly a "FYI" ticket, but if you have suggestions I could try with the (a) LiveISO I'd be happy to.

**Comment by demmm** [comment]
Not clear if this is an older system is reasonable new. (2010 or later)
Can you post the outcome of
```
inxi -G
```
Also try to use XRender (if older grfx card, then this is a known issue, Plasma using gfx card RAM, which is not available on older cards).
systemsettings > display & monitor > compositor > rendering backend
switch from OpenGl 2.0 to XRender

**Comment by RJVB** [comment]
On Friday July 01 2016 08:54:39 demmm wrote:

It's

>Can you post the outcome of
>```
>inxi -G
>```

On the Ubuntu (stable) system I get this:
```
Graphics:  Card: Intel Device 22b1 X.Org: 1.17.2 drivers: intel (unloaded: fbdev,vesa) Resolution: 1366x768@60.1hz 
           GLX Renderer: Mesa DRI Intel HD Graphics (Cherryview) GLX Version: 3.0 Mesa 11.0.2
```

The N3150 was released in early 2015:
http://www.notebookcheck.net/Intel-Celeron-N3150-SoC.146641.0.html


>Also try to use XRender (if older grfx card, then this is a known issue, Plasma using gfx card RAM, which is not available on older cards).
>systemsettings > display & monitor > compositor > rendering backend
>switch from OpenGl 2.0 to XRender

Both KWin4 and KWin5 work correctly with OpenGL 3.1 on this IGP. Switching off compositing in KWin doesn't resolve any issues in applications that don't respect that setting (like Google Chrome).
From exchanges elsewhere I'm convinced that the underlying issue is lacking support in the i915 driver and possibly in the DRI3 libraries.
BTW, upgrading from 4.5.6 to 4.5.7 made a huge difference.

Another thing: the hardware inspector on the ISO fails to recognise quite a few hardware items.

R.

Full output from lspci:
```
%> lspci -v
00:00.0 Host bridge: Intel Corporation Device 2280 (rev 21)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, fast devsel, latency 0
        Kernel driver in use: iosf_mbi_pci

00:02.0 VGA compatible controller: Intel Corporation Device 22b1 (rev 21) (prog-if 00 [VGA controller])
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, fast devsel, latency 0, IRQ 119
        Memory at 80000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 90000000 (64-bit, prefetchable) [size=256M]
        I/O ports at f000 [size=64]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: [d0] Power Management version 2
        Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [b0] Vendor Specific Information: Len=07 <?>
        Kernel driver in use: i915

00:0b.0 Signal processing controller: Intel Corporation Device 22dc (rev 21)
        Flags: bus master, fast devsel, latency 0, IRQ 120
        Memory at 8141f000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: [40] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [50] Power Management version 3
        Kernel driver in use: proc_thermal

00:13.0 SATA controller: Intel Corporation Device 22a3 (rev 21) (prog-if 01 [AHCI 1.0])
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 117
        I/O ports at f060 [size=32]
        Memory at 8141e000 (32-bit, non-prefetchable) [size=2K]
        Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [70] Power Management version 3
        Capabilities: [a8] SATA HBA v1.0
        Kernel driver in use: ahci

00:14.0 USB controller: Intel Corporation Device 22b5 (rev 21) (prog-if 30 [XHCI])
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, medium devsel, latency 0, IRQ 115
        Memory at 81400000 (64-bit, non-prefetchable) [size=64K]
        Capabilities: [70] Power Management version 2
        Capabilities: [80] MSI: Enable+ Count=1/8 Maskable- 64bit+
        Kernel driver in use: xhci_hcd

00:1a.0 Encryption controller: Intel Corporation Device 2298 (rev 21)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, fast devsel, latency 0, IRQ 121
        Memory at 81100000 (32-bit, non-prefetchable) [size=1M]
        Memory at 81000000 (32-bit, non-prefetchable) [size=1M]
        Capabilities: [80] Power Management version 3
        Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Kernel driver in use: mei_txe

00:1b.0 Audio device: Intel Corporation Device 2284 (rev 21)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, fast devsel, latency 0, IRQ 123
        Memory at 81414000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: [50] Power Management version 2
        Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Kernel driver in use: snd_hda_intel

00:1c.0 PCI bridge: Intel Corporation Device 22c8 (rev 21) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0
        Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
        I/O behind bridge: 0000e000-0000efff
        Memory behind bridge: 81300000-813fffff
        Prefetchable memory behind bridge: 00000000a0000000-00000000a00fffff
        Capabilities: [40] Express Root Port (Slot+), MSI 00
        Capabilities: [80] MSI: Enable- Count=1/1 Maskable- 64bit-
        Capabilities: [90] Subsystem: CLEVO/KAPOK Computer Device 5108
        Capabilities: [a0] Power Management version 3
        Capabilities: [100] #00
        Capabilities: [200] L1 PM Substates
        Kernel driver in use: pcieport

00:1c.1 PCI bridge: Intel Corporation Device 22ca (rev 21) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0
        Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
        I/O behind bridge: 00001000-00001fff
        Memory behind bridge: 81200000-812fffff
        Prefetchable memory behind bridge: 0000000081500000-00000000816fffff
        Capabilities: [40] Express Root Port (Slot+), MSI 00
        Capabilities: [80] MSI: Enable- Count=1/1 Maskable- 64bit-
        Capabilities: [90] Subsystem: CLEVO/KAPOK Computer Device 5108
        Capabilities: [a0] Power Management version 3
        Capabilities: [100] #00
        Capabilities: [200] L1 PM Substates
        Kernel driver in use: pcieport

00:1f.0 ISA bridge: Intel Corporation Device 229c (rev 21)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, medium devsel, latency 0
        Capabilities: [e0] Vendor Specific Information: Len=0c <?>
        Kernel driver in use: lpc_ich

00:1f.3 SMBus: Intel Corporation Device 2292 (rev 21)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: medium devsel, IRQ 5
        Memory at 81418000 (32-bit, non-prefetchable) [size=32]
        I/O ports at f040 [size=32]
        Capabilities: [50] Power Management version 3

01:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5286 PCI Express Card Reader (rev 01)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, fast devsel, latency 0, IRQ 116
        Memory at 81300000 (32-bit, non-prefetchable) [size=64K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [b0] MSI-X: Enable- Count=1 Masked-
        Capabilities: [d0] Vital Product Data
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Virtual Channel
        Capabilities: [160] Device Serial Number 00-00-00-01-00-4c-e0-00
        Kernel driver in use: rtsx_pci

01:00.2 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller (rev 06)
        Subsystem: CLEVO/KAPOK Computer Device 5108
        Flags: bus master, fast devsel, latency 0, IRQ 118
        I/O ports at e000 [size=256]
        Memory at 81310000 (64-bit, non-prefetchable) [size=4K]
        Memory at a0000000 (64-bit, prefetchable) [size=16K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 01
        Capabilities: [b0] MSI-X: Enable- Count=4 Masked-
        Capabilities: [d0] Vital Product Data
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [160] Device Serial Number 01-00-00-00-36-4c-e0-00
        Kernel driver in use: r8169

02:00.0 Network controller: Intel Corporation Wireless 7265 (rev 61)
        Subsystem: Intel Corporation Wireless-N 7265
        Flags: bus master, fast devsel, latency 0, IRQ 122
        Memory at 81200000 (64-bit, non-prefetchable) [size=8K]
        Capabilities: [c8] Power Management version 3
        Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [40] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 5c-e0-c5-ff-ff-a3-68-c1
        Capabilities: [14c] Latency Tolerance Reporting
        Capabilities: [154] L1 PM Substates
        Kernel driver in use: iwlwifi
```

**Comment by demmm** [comment]
Since this is newer hardware, best advice to give (if you decide to install KaOS), use the linux-next kernel, so you can follow possible needed fixes for this system:
https://kaosx.us/docs/kernels/

And no, switching to XRender for this new hardware will not help :)

**Comment by RJVB** [comment]
On Friday July 01 2016 09:22:50 demmm wrote:

>Since this is newer hardware, best advice to give (if you decide to install KaOS), use the linux-next kernel, so you can follow possible needed fixes for this system:
>https://kaosx.us/docs/kernels/

That's supposing that the system remains stable long enough to allow to complete the installation ;)
I'd have to install to an external on another system, switch to using linux-next and then rsync from the external to my target partition. Best way to avoid having to tinker with GRUB, too O:-)

My main reason for raising the observations here was that I thought you might be feeding back this kind of info to the kernel guys. Do you?

R.

**Comment by demmm** [comment]
You mean upstream kernel developers?  No KaOS can't create bug reports for hardware it doesn't own, or issues not seen but on specific users hardware.  If you know this is an upstream kernel issue, best you report with your hardware logs.

**Comment by demmm** [comment]
Could it be that this is not a kernel issue but an issue with latest mesa/intel?
This commit could be the needed fix:
https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/commit/?id=9154dff9aedad3271f629edb1ccc9c8d273ca7bc

**Comment by RJVB** [comment]
On Saturday July 02 2016 12:56:41 demmm wrote:
>Could it be that this is not a kernel issue but an issue with latest mesa/intel?
>This commit could be the needed fix:
>https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/commit/?id=9154dff9aedad3271f629edb1ccc9c8d273ca7bc

That certainly won't hurt, but since I've been seeing the same kind of issue with an older mesa (but not with kernel 4.5) it's probably not the only culprit.

There is revert of an interrupt handling patch in 4.6.3 that seems much more likely to be helpful; the description in the commit message makes me think of the symptoms I'm seeing.
Apparently 4.7 will have a better patch that's "too big to include in 4.6" (?!)

R.

**Comment by demmm** [comment]
linux-next is currently at 4.6.3, 4.7 will be used as linux-next with either 47RC7 or 4.7.0
But as you said, probably no use in this case, since the system won't stay stable long enough to do an install & switch to linux-next.

**Comment by bvbfan** [comment]
[code]dmesg | grep -i "segafault\|error"
cat /var/log/Xorg.0.log | gerp EE
cat /var/log/Xorg.0.log.old | gerp EE[/code]
My new laptop will be with i5-6200U (Skylake) i make stability test and i can't notice glitches onr instability for 30 min. Can you apply new Xorg driver with glamor
https://forum.kaosx.us/d/1470-new-ddx-xorg-drivers
Still not tested by me on real intel hardware.

**Comment by RJVB** [comment]
On Saturday July 02 2016 22:01:19 Anthony Fieroni wrote:
>[code]dmesg | grep -i "segafault\|error"
>cat /var/log/Xorg.0.log | gerp EE
>cat /var/log/Xorg.0.log.old | gerp EE[/code]

gerp?

>My new laptop will be with i5-6200U (Skylake) i make stability test and i can't notice glitches onr instability for 30 min. Can you apply new Xorg driver with glamor
>https://forum.kaosx.us/d/1470-new-ddx-xorg-drivers
>Still not tested by me on real intel hardware.

Is this an answer in my thread or posted in the wrong thread?

I'm not sure if there's a lot of interest in forcing DRI3 mode if according to a previous post the DRI3 implementation is incomplete for CherryView graphics...

R.

**Comment by bvbfan** [comment]
I broke screen on my current laptop and i use TV, about 3m, i don't see the error, i mean grep :)
On second question, this is for you, new DDX Xorg drivers using glamor egl, why you think i'm in wrong? Yah, i'm still testing on radeon, but it's way better than glx ones.

**Comment by demmm** [comment]
This is not a graphics driver issues, but kernel.
As noted here:
https://forum.kaosx.us/d/1528-solved-system-freezes-with-2016-06-and-or-kernel-4-6-2/5
Using linux-next 4.6.3 fixes the issue (as already suspected in this thread too).

Issue can't be fixed on current ISO, so this report will stay open until new ISO is out later this month or in August.

**Comment by RJVB** [comment]
On Sunday July 03 2016 05:26:11 demmm wrote:

>Using linux-next 4.6.3 fixes the issue (as already suspected in this thread too).

That thread seemed to be talking about the 4.5 kernel series, but whatever ...

>Issue can't be fixed on current ISO, so this report will stay open until new ISO is out later this month or in August.

... at the rate they're spewing updates you might be looking at 4.6.4 or even 4.6.5 ... with its own set of regressions ;)

R.

**Comment by bvbfan** [comment]
RJVB, i got the laptop with skylake, DDX Xorg driver works great, tear free is enabled by default
[code][live@localhost ~]$ cat /var/log/Xorg.0.log | grep -i glamor
[ 15753.758] (**) modeset(0): Option "AccelMethod" "glamor"
[ 15753.758] (II) Loading sub module "glamoregl"
[ 15753.758] (II) LoadModule: "glamoregl"
[ 15753.759] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[ 15753.799] (II) Module glamoregl: vendor="X.Org Foundation"
[ 15753.799] (II) glamor: OpenGL accelerated X.org driver based.
[ 15753.815] (II) glamor: EGL version 1.4 (DRI2):
[ 15753.817] (II) modeset(0): glamor initialized[/code]
DRI3 is still not implemented

**Comment by RJVB** [comment]
On Sunday July 10 2016 04:28:26 Anthony Fieroni wrote:
>RJVB, i got the laptop with skylake, DDX Xorg driver works great, tear free is enabled by default

Yes, on my wife's i3/SkyLake laptop the KaOS Live image works fine too.

R
