### ISSUE TITLE
free: Multiple unit options doesn't make sense.

### ISSUE THREAD

**Issue by winny-** [KaOSx/live-uefi#14]
it appears `alias free='free -m'` breaks changing the units. Perhaps a different approach could be used to invoke `free` with `-m` in absence of a unit flag?

**Comment by demmm** [comment]
>breaks changing the units
What units are broken?

**Comment by winny-** [comment]
If one runs `free -g` it will yield error message: `free: Multiple unit options doesn't make sense.`. This is because `free` refuses to continue if multiple unit flags are passed. This has a potential to confuse new users (they might misunderstand the default behavior of free to print out mebibytes).

**Comment by demmm** [comment]
Removed from bashrc for next ISO, issue will stay open until that ISO is released.
