### ISSUE TITLE
Link to this site is broken

### ISSUE THREAD

**Issue by Tanzmusikus** [KaOSx/live-uefi#18]
Hello,
I went from https://kaosx.us/docs/bugs/ and choosed the link called "Live ISO Probleme" (translated to german or [Deutsch]) https://github.com/KaOSx/live-uefi/issues%7D ... then I landed on 404 error.

The problem depends on translation. If I choose english, nederlands or francais - there's no problem, because they are all english.
Best regards!

**Comment by ShalokShalom** [comment]
> Hello, I went from https://kaosx.us/docs/bugs/ and choosed the link called "Live ISO Probleme" (translated to german or [Deutsch]) https://github.com/KaOSx/live-uefi/issues%7D ... then I landed on 404 error.
> 
> The problem depends on translation. If I choose english, nederlands or francais - there's no problem, because they are all english. Best regards!

That is the correct link:

https://github.com/KaOSx/live-uefi/issues
