### ISSUE TITLE
KaOS Installation bug

### ISSUE THREAD

**Issue by iNzz** [KaOSx/live-uefi#2]
Before i made this excact issue , but on the wrong page , it was closed so i'll just post it agian.

Hello! I have a problem with KaOS while installing it.

What I do :

Create a Bootable Usb with KaOS 2015.ISO on it , have an 80gb hard disk,

Launch KaOS live , click for installation , select everything properly how i want it , KaOS installation begins, at the end , about 0.5 seconds away from the "creating user" text below the installation bar, an error occurs and it says:

Installation Failed

Boost.Python error in job "Run script userkf5/main.py".

class 'AttributeError'

'Nonetype'object has no attribiute 'group'
Traceback:

File "/usr/lib/calamares/modules/userkf5/main.py" , line 121, in run print (m.group(0)).

I also created a thread on 4chan.org , if you want to see the thread , here is the link!

http://boards.4chan.org/g/thread/47915533/kaos-install-bug

Ofcourse i checked the /userkf5/main.py and it seems to be a Python programming script , i checked line 121 and it's just this line:

print (m.group(0)).

What i tried to do:

Using octopi to install calamares (seems to be some sort of c/c++ compiler) , after i've installed it , the installation won't even begin.

Help?

**Comment by demmm** [comment]
Did you not read the reply on your other entry?  Why repeat useless info, it was posted what is needed.  Not even clear at all if you just need help creating live media correctly.

**Comment by demmm** [comment]
No response from submitter about providing needed logs.  Not clear if user applied any of the supported methods to create live media.
