### ISSUE TITLE
Konqueror rendering problems

### ISSUE THREAD

**Issue by freemint** [KaOSx/live-uefi#3]
On the live cd Konqueror is not able to render websites as intended. Inparticualr he is not able to render font when inserting in to a text field

**Comment by demmm** [comment]
Live-uefi issues are for problems booting the live ISO, issues with hardware recognition, drivers loading.
It is not for reporting an issue with loading an url in a browser.
Open an apps issue and give proper info, see:
http://kaosx.us/asking-and-reporting-the-smart-way/
