### ISSUE TITLE
KaOS 2015.06 Installation error

### ISSUE THREAD

**Issue by jose147** [KaOSx/live-uefi#7]
Hi,

I decided today to start my runaway with KaOS, but in the middle of the process a error in calamares appear.

There is the log to fix it

http://pastebin.com/QQJbaCFq

**Comment by demmm** [comment]
What ISO used, exact name and date?
How was the live media created?
See for supported options:
http://kaosx.us/bootable-usb-flash-drive-creation/
http://kaosx.us/dvd-iso-creation/

And more questions to answer for proper reporting:
http://kaosx.us/asking-and-reporting-the-smart-way/
http://kaosx.us/asking-and-reporting-the-smart-way/#Info_to_provide_for_Installation_Issues

**Comment by jose147** [comment]
DD dont work, only crash withtout any kind of error log.

Imagewriter dont support iso files only .raw files.

I downloaded the iso from there:

http://sourceforge.net/projects/kaosx/files/ISO/KaOS-2015.06-x86_64.iso

**Comment by demmm** [comment]
Not answering how you created the live media, only what didn't work.
Issues are not for user support.  If you did not create live media with any of the supported options, then this is not a bug in live-uefi but a user needing help creating correct live-media.
Also no answer if you checked any of the other checkpoints listed for you.

**Comment by jose147** [comment]
MD5 was correct, the media was created with rufus, because the provided solutions DIDN'T WORK,, the live cd worked well until the fail in installation appeared.

I used pastebin to "report it in the smart way" so I obvius this point

**Comment by demmm** [comment]
RUFUS is not supported, known to create broken media, not a live-uefi issue
