### ISSUE TITLE
2015.10 live slow on Atom CPU

### ISSUE THREAD

**Issue by raul338** [KaOSx/live-uefi#8]
```
System:    Host: rau-net Kernel: 4.1.9-1 x86_64 (64 bit gcc: 4.9.3) Desktop: KDE Plasma 5.4.2 (Qt 5.5.0)
           Distro: KaOS rolling
Machine:   Mobo: SAMSUNG model: NC210/NC110 Bios: Phoenix v: 00VG.M000.20110105.RHU date: 01/05/2011
CPU:       Dual core Intel Atom N570 (-HT-MCP-) cache: 512 KB
           flags: (lm nx sse sse2 sse3 ssse3 vmx) bmips: 6653
           clock speeds: max: 1667 MHz 1: 1000 MHz 2: 1667 MHz 3: 1000 MHz 4: 1000 MHz
Graphics:  Card: Intel Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller bus-ID: 00:02.0
           Display Server: X.Org 1.17.2 driver: intel Resolution: 1024x600@60.01hz
           GLX Renderer: Mesa DRI Intel Pineview M GLX Version: 2.1 Mesa 11.0.2 Direct Rendering: Yes
Audio:     Card Intel NM10/ICH7 Family High Definition Audio Controller driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.1.9-1                                                
Network:   Card-1: Broadcom BCM4313 802.11bgn Wireless Network Adapter                                         
           driver: bcma-pci-bridge bus-ID: 05:00.0                                                             
           IF: wlp5s0b1 state: up mac: <filter>                                                                
           Card-2: Realtek RTL8101E/RTL8102E PCI Express Fast Ethernet controller                              
           driver: r8169 v: 2.3LK-NAPI port: 2000 bus-ID: 09:00.0                                              
           IF: enp9s0 state: down mac: <filter>                                                                
Drives:    HDD Total Size: 320.1GB (11.2% used) ID-1: /dev/sda model: Hitachi_HTS54323 size: 320.1GB           
Partition: ID-1: / size: 64G used: 32G (50%) fs: xfs dev: /dev/sda7                                            
           ID-2: swap-1 size: 2.13GB used: 0.00GB (0%) fs: swap dev: /dev/sda6                                 
Sensors:   System Temperatures: cpu: 55.0C mobo: N/A                                                           
           Fan Speeds (in rpm): cpu: N/A                                                                       
Info:      Processes: 138 Uptime: 23 min Memory: 804.1/1995.1MB Init: systemd runlevel: 5 Gcc sys: 4.9.3       
           Client: Shell (bash 4.3.421) inxi: 2.2.28 
```
Note: Info took from already installed KaOS. It runs well

But for 2015.10 live is horribly slowins
journal log: http://pastebin.com/NZJhg8Sv

**Comment by demmm** [comment]
Would you mind installing htop in live mode (or it might show clear enough in ksysguard too) to see what is using all the CPU?
Anything in ~/.xsession-errors?

**Comment by raul338** [comment]
~/.xsession-errors :  http://pastebin.com/xE6shE3j

In ksysguard kwin_x11 is always at 50%-100% CPU

**Comment by demmm** [comment]
Can you log out of live mode, then log in using the Wayland session option?  Won't be very usable, but at least check ksysguard to see if kwin_wayland is quiet.  In case note sure, login for live mode is username: live, passw: live

**Comment by demmm** [comment]
A few more questions trying to compare your installed system with live mode.
Do you have kdeconnect-kde installed?  The whole ktp group (kde-telepathy)?  Printer packages installed?

**Comment by raul338** [comment]
Wayland works fine (not slow, some bugs/segfaults with kdeinit)
And yes, i have kdeconnect & telepathy pack installed in normal system

**Comment by raul338** [comment]
Telephaty & printers were installed by default.

**Comment by demmm** [comment]
Great, that narrows it down to new kwin.  Can't be a graphics driver or kernel issue now.  Still no idea though why your installed system is not effected the same way.

Yes, those are all installed by default but since the error logs mention kdeconnect, ktp and printers I thought to check to see if you removed them from your installed system.

**Comment by demmm** [comment]
Are you using a 20-intel.conf on installed system, setting to use uxa (instead of default and in live mode used sna)?

**Comment by raul338** [comment]
My system was installed with 2015.03 iso and updated over time. That system has no issues.

The issue is only with 2015.10 iso, also i can install 2015.10 on a separate partition to continue testing

**Comment by demmm** [comment]
No need to install, live mode gives enough info so far, just curious if you added the intel.conf to your current install.

**Comment by raul338** [comment]
I have an intel.conf file but to only add
Option "Backlight" "intel_backlight"

**Comment by demmm** [comment]
OK
Can you stop sddm, remove most "live" user config files and restart sddm?
sudo systemctl stop sddm
Ctrl-Alt-F2
Login with live/live
rm ~./config
rm ~/.kde4
sudo systemctl start sddm

**Comment by raul338** [comment]
First try: as soon i stopped sddm my screen was with 0 brightness.. Had to start with i915.modeset=0
Second try: worked well. Live is more responsive but now plasmashell is taking 40% of cpu (minimum of 20%)

**Comment by raul338** [comment]
However now is using vesa instead of intel driver. Max resolution i have is 800*600 haha

**Comment by demmm** [comment]
When you stop sddm it does not switch tty, you need to use Alt-Ctrl-F2 for that.
Might want to try in that order, first switch tty, then stop sddm while in tty2, remove configs, then restarts sddm.

**Comment by raul338** [comment]
I did that, even switch tty2, remove configs, restart sddm. Then screen goes black as if it were shutted down.

**Comment by demmm** [comment]
OK
Next trial.....
Go to tty2 again after rebooting.
Stop sddm, then start plasma without sddm, just use "startkde"
And can you post the /etc/sddm.conf from your installed system?  Checking to see if you merged the changes for new sddm/wayland options.

**Comment by raul338** [comment]
even switching tty3 after stopping sddm. I blindly login and type startkde i see nothing (switching tty1, tty2, tty3)

my /etc/sddm.conf : http://pastebin.com/9Z36dKnU

**Comment by demmm** [comment]
OK, not a wayland difference....
One more try to boot without sddm
At the start of live mode add 3 to the kernel line, that way it will start in console mode.
Login with live/live, and type "startx"

**Comment by raul338** [comment]
After startx it booted normal, but it still slow.

Didn't know about the 3 kernel line. Thanks for that :D

**Comment by raul338** [comment]
Looking at the [bugtrack](https://bugs.kde.org/show_bug.cgi?id=352068) i found that it is the compositor
Pressing Shift + Alt + F12 (i thinks it disables the compositor) in live mode it goes super snappy
However none of the settings recomended in that links works to make the desktop snappy with compositor enabled

**Comment by demmm** [comment]
OK, so also not sddm related.
I did forget to ask one thing about your installed system, do you use xrender or opengl?  systemsettings > display & monitor > compositor >rendering backend
Test in live mode too to set to xrender (with compositor enabled)

**Comment by raul338** [comment]
Yes with XRender works ok. And yes, in my system i use opengl 2 (love the wobblywindows)

**Comment by demmm** [comment]
It has to be a settings difference for the "live" user and your user (installed)
What menu launcher is in use on installed system?
Maybe restarting plasmashell from the console in live mode will show something.
kquitapp5 plasmashell && plasmashell

**Comment by raul338** [comment]
I edited my last answer... I'm using XRender so that is why is so snappy.

**Comment by demmm** [comment]
OK, then this can be closed now, it is a long known issue that older cards don't have the GPU RAM that plasma 5 uses now.  Those systems always need to switch to XRender, not a bug, just the best way to have a DE that works with modern hardware and also performs great with older/less powerful setups.

**Comment by raul338** [comment]
Yep, maybe there's the need of some script that detect old gpu/cpu and turn to Xrender...
Anyway... Closing
